#include <bOoM/color.hpp>
#include <bOoM/colorf.hpp>
namespace bOoM {

color const color::red         = color( COLORCHANNEL_RANGE_MAX, COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MIN );
color const color::green       = color( COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MAX, COLORCHANNEL_RANGE_MIN );
color const color::blue        = color( COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MAX );
color const color::white       = color( COLORCHANNEL_RANGE_MAX, COLORCHANNEL_RANGE_MAX, COLORCHANNEL_RANGE_MAX );
color const color::black       = color( COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MIN );
color const color::transparent = color( COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MIN, COLORCHANNEL_RANGE_MIN );

colorf const colorf::red         = colorf( COLORFCHANNEL_RANGE_MAX, COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MIN );
colorf const colorf::green       = colorf( COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MAX, COLORFCHANNEL_RANGE_MIN );
colorf const colorf::blue        = colorf( COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MAX );
colorf const colorf::white       = colorf( COLORFCHANNEL_RANGE_MAX, COLORFCHANNEL_RANGE_MAX, COLORFCHANNEL_RANGE_MAX );
colorf const colorf::black       = colorf( COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MIN );
colorf const colorf::transparent = colorf( COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MIN, COLORFCHANNEL_RANGE_MIN );

} //namespace bOoM

